# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "inventec/centos7"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)"
  config.ssh.insert_key = false
  config.ssh.private_key_path = './key/id_rsa'
  # config.ssh.username = "vagrant"
  # config.ssh.password = "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = 4
  end

  # config.vm.provision "shell", inline: <<-SHELL
  
  # SHELL
  
  # config.vm.provision "shell", path: "setup.sh"
end
